
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 02 21:22:48 COT 2021
//----------------------------------------------------

package SoloLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 19;
  public static final int Coma = 32;
  public static final int Llave_c = 26;
  public static final int Op_booleano = 22;
  public static final int Unsigned = 54;
  public static final int Llave_a = 25;
  public static final int If = 6;
  public static final int T_dato = 4;
  public static final int Byte = 36;
  public static final int Default = 46;
  public static final int Else = 7;
  public static final int Cout = 58;
  public static final int Enum = 47;
  public static final int Break = 42;
  public static final int Goto = 49;
  public static final int Corchete_c = 28;
  public static final int Doble = 12;
  public static final int Extern = 48;
  public static final int Corchete_a = 27;
  public static final int Union = 52;
  public static final int Long = 39;
  public static final int Punto = 31;
  public static final int Parent_c = 24;
  public static final int Return = 51;
  public static final int Parent_a = 23;
  public static final int While = 9;
  public static final int Division = 17;
  public static final int Int = 11;
  public static final int Float = 40;
  public static final int Cadena = 5;
  public static final int For = 10;
  public static final int EOF = 0;
  public static final int P_coma = 30;
  public static final int Printf = 57;
  public static final int error = 1;
  public static final int Switch = 41;
  public static final int Linea = 2;
  public static final int Char = 38;
  public static final int D_puntos = 37;
  public static final int Op_atribucion = 20;
  public static final int ERROR = 35;
  public static final int Do = 8;
  public static final int Continue = 45;
  public static final int Case = 43;
  public static final int Op_logico = 18;
  public static final int Short = 53;
  public static final int Register = 50;
  public static final int Scanf = 59;
  public static final int Const = 44;
  public static final int Identificador = 33;
  public static final int Cin = 60;
  public static final int Struct = 55;
  public static final int Resta = 15;
  public static final int Typedef = 56;
  public static final int Multiplicacion = 16;
  public static final int Op_incremento = 21;
  public static final int Numero = 34;
  public static final int Suma = 14;
  public static final int Main = 29;
  public static final int Igual = 13;
  public static final int Comillas = 3;
}

